#!/usr/bin/env bash

export PID_FILE_PATH="/tmp/battery.pid"
export LOG_FILE_PATH="/tmp/battery.log"
export LOG_ERROR_FILE_PATH="/tmp/battery.error.log"

. ./lib/services.sh
. ./etc/settings.sh

if [ ! -e "${BAR_FIFO}" ]; then
	mkfifo ${BAR_FIFO}
fi

run-battery() {
	N=('\ue15f' '\ue160' '\ue161' '\ue162' '\ue163' '\ue164' '\ue165' '\ue166' '\ue167' '\ue168')
	B='\ue215'

	
	while :; do
		echo -n "BATTERY|"
		a=$(apm -l)
		echo -e ${B}${N[${a:0:1}]}${N[${a:1:1}]}
		sleep 60
	done > ${BAR_FIFO}
}

action="${1}"
serviceName="report battery to fifo"
command="run-battery"

serviceMenu "$action" "$serviceName" "$command"

