#!/usr/bin/env bash

export PID_FILE_PATH="/tmp/datetime.pid"
export LOG_FILE_PATH="/tmp/datetime.log"
export LOG_ERROR_FILE_PATH="/tmp/datetime.error.log"

. ./lib/services.sh
. ./etc/settings.sh

if [ ! -e "${BAR_FIFO}" ]; then
	mkfifo ${BAR_FIFO}
fi

run-datetime() {
	N=('\ue15f' '\ue160' '\ue161' '\ue162' '\ue163' '\ue164' '\ue165' '\ue166' '\ue167' '\ue168')
	C='\ue192'
	I='\ue1b9'
	
	while :; do
		echo -n "DATETIME|"
		h=$(date +"%H")
		m=$(date +"%M")
		echo -e ${I}${N[${h:0:1}]}${N[${h:1:1}]}${C}${N[${m:0:1}]}${N[${m:1:1}]}
		sleep 60
	done > ${BAR_FIFO}
}

action="${1}"
serviceName="report datetime to fifo"
command="run-datetime"

serviceMenu "$action" "$serviceName" "$command"

